class AlbertoX3Error(Exception): ...
class DeveloperError(AlbertoX3Error): ...
class DeveloperArgumentError(DeveloperError): ...

class GatherAnyError(Exception):
    idx: int
    exception: Exception

    def __init__(self, idx: int, exception: Exception): ...

class UnrecognisedBooleanError(AlbertoX3Error): ...
