name: Bug Report
description: Report broken or incorrect behaviour.
labels: ["bug"]
title: "[BUG] Your Title Here"

assignees:
  - AlbertUnruh
body:
  - type: markdown
    attributes:
      value: >
        Thanks for taking the time to fill out a bug report.

        Note: English and German are both supported languages for PRs.


  - type: input
    attributes:
      label: "Alberto-X3 Version"
      description: "The version from Alberto-X3. *(retrieve it via ``AlbertoX3.utils.get_lib_version()``)*"
    validations:
      required: true
  - type: textarea
    attributes:
      label: "Describe the Bug"
      description: "A simple summary of your bug report"
    validations:
      required: true
  - type: textarea
    attributes:
      label: "Expected Results"
      description: >
        A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    attributes:
      label: "Minimal Reproducible Code"
      description: >
        A short snippet of code that showcases the bug.
      render: python
  - type: textarea
    attributes:
      label: Traceback
      description: >
        Was there a traceback?
    validations:
      required: false
  - type: checkboxes
    attributes:
      label: Checklist
      description: >
        Let's make sure you've properly done due diligence when reporting this issue!
      options:
        - label: I have searched the open issues for duplicates.
          required: true
        - label: I have shown the entire traceback, if possible.
          required: true
        - label: I have removed my token from display, if visible.
          required: true
  - type: textarea
    attributes:
      label: Additional Information
      description: Any other information about the problem.
