name: Extension Request
description: Request new extensions.
title: "[EXT FEAT] Your Title Here"
labels: ["extension request"]

body:
  - type: markdown
    attributes:
      value: >
        Thanks for the extension request.

        Note: English and German are both supported languages for Extension Requests.


  - type: input
    attributes:
      label: "Extension Name"
      description: "What would you call the extension?"
    validations:
      required: true

  - type: textarea
    attributes:
      label: What are the benefits of having such an extension? Please describe.
      description: A clear and concise description of what the extension should do. Ex. It helps moderating the server because [...]
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe the solution you'd like
      description: >
         A clear and concise description of what you want to happen.
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Checklist
      options:
        - label: I have searched the open extension requests for ``duplicates``.
          required: true
        - label: I have searched the closed extension requests for ``wontadd``'s.
          required: true
- type: textarea
    attributes:
      label: Additional Information
      description: >
        A clear and concise description of what you expected to happen.
