name: Pre-commit

on:
  push:
    branches: [ stable, develop ]
  pull_request:
    branches: [ stable, develop ]

jobs:
  linter_name:
    name: Pre-commit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v2.3.1
        with:
          python-version: '3.10'
      - name: Setup annotations
        uses: PennyDreadfulMTG/setup-linters@main
      - name: Install Pre-commit
        run: |
          pip install pre-commit
      - name: Run Pre-commit
        run: |
          pre-commit run --all-files
